### ISSUE TITLE
Create the conf_apps.cfg

### ISSUE THREAD

**Issue by wesleydmscn** [wesleydmscn/opl-helper-for-linux#11]
Create conf_apps.cfg and detect duplicates

### Tasks:

- [ ] With everything prepared, start listing the APPS in a file conf_apps.cfg.
- [ ] With everything prepared, start listing the PS1 Games in the conf_apps.cfg file.
- [ ] Check for duplicates in the conf_apps.cfg file and remove them.

Acceptance Criteria: At this point, the user must have his disk ready to use in his Playstation 2 OPL
