### ISSUE TITLE
Prepare cue/bin files to be converted to .VCD

### ISSUE THREAD

**Issue by wesleydmscn** [wesleydmscn/opl-helper-for-linux#8]
Create a structure where PS1 games should be placed to be converted.

### Tasks:

- [ ] Create the staging structure.
- [ ] Separate converted files to be transferred.
- [ ] Return a list of converted games to the user.

Acceptance Criteria: The user must be able to concentrate the cue/bin files in one place to get them all converted.
