### ISSUE TITLE
Detect disks available for automation

### ISSUE THREAD

**Issue by wesleydmscn** [wesleydmscn/opl-helper-for-linux#9]
Detect disks for user to choose.

### Tasks:

- [ ] Save chosen disk address.
- [ ] Trigger the module that detects APPS passing the current disk.
- [ ] Trigger the module that detects VCD by passing the current disc.

Acceptance Criteria: At this point it should be possible to know which APPS/VCD are on the disk and if the folder structure is correct.
